標準出力メッセージとエラーメッセージを統一し、テスト実行のメッセージ表示も合わせて見直し。

diff --git a/git-svn-overwrite b/git-svn-overwrite
--- a/git-svn-overwrite
+++ b/git-svn-overwrite
@@ -59,7 +59,7 @@ end
 if ($gitrepo == "" || $gitbranch == "" || $svnrepo == "" || $svnbranch == "") then
   echo "ERROR: Argument error."
   echo "ERROR: Usage: $ $0 [--dry-run] [-f(--commit-hash-file) file_name] git-repo git-branch svn-repo svn-branch"
-  exit 2
+  exit 1
 endif
 
 set datetime = `date +"%Y%m%d%H%M%S"`
@@ -73,18 +73,27 @@ set commit_hash_temp_file = ".commit_hash_temp_file"
 touch $commit_hash_file
 set prev_git_commit = `cat $commit_hash_file`
 
-echo "[git-svn-overwrite]"
-
 if ($dry_run_mode == "off") then
 else
-  echo "dry-running..."
+  echo "Dry running..."
 endif
 
 mkdir -p $tempdir
-cd $tempdir
 
-git clone -b $gitbranch $gitrepo git
-svn checkout $svnrepo/$svnbranch svn
+(git clone -b $gitbranch $gitrepo $tempdir/git > /dev/null) >& /dev/null
+if ($? != 0) then
+  echo "ERROR: Git repository clone error."
+  echo "ERROR: Git-repository: [$gitrepo/$gitbranch]"
+  exit 2
+endif
+(svn checkout $svnrepo/$svnbranch $tempdir/svn > /dev/null) >& /dev/null
+if ($? != 0) then
+  echo "ERROR: Svn repository checkout error."
+  echo "ERROR: Svn-repository: [$svnrepo/$svnbranch]"
+  exit 3
+endif
+
+cd $tempdir
 
 #
 # list differ repository to svn and git.
@@ -104,7 +113,7 @@ awk '\
       print "mv -f", p "/" $4, n "/"; } \
   /^Files .* differ$/ \\
     { print "mv -f", $4 " " $2; }' \
-$diff_file | csh -fx
+$diff_file | csh -f
 
 #
 # create operating svn-repository command and execute.
@@ -124,7 +133,7 @@ awk 'BEGIN{ print "cd svn" ;} \
         n = substr($3, 5, length($3)-5) "/"; \
       } \
       print "svn add", n $4; }' \
-$diff_file | csh -fx
+$diff_file | csh -f > /dev/null
 
 #
 # create commit logs and save current "HEAD" commit value.
@@ -135,10 +144,26 @@ echo "Date: $date" >>! ../$comment_file
 echo "" >>! ../$comment_file
 if ($prev_git_commit == "") then
   git log --graph HEAD >>! ../$comment_file
+  if ($? != 0) then
+    echo "ERROR: Git repository log error."
+    echo "ERROR: Git-repository: [$gitrepo/$gitbranch]"
+    exit 4
+  endif
 else
   git log --graph ^${prev_git_commit} HEAD >>! ../$comment_file
+  if ($? != 0) then
+    echo "ERROR: Git repository log error."
+    echo "ERROR: Git-repository: [$gitrepo/$gitbranch]"
+    exit 5
+  endif
 endif
 git log -1 --pretty=format:"%H" >! ../$commit_hash_temp_file
+if ($? != 0) then
+  echo "ERROR: Git repository log error."
+  echo "ERROR: Git-repository: [$gitrepo/$gitbranch]"
+  exit 6
+endif
+set commit_hash_value = `cat ../$commit_hash_temp_file`
 cd ..
 
 #
@@ -147,25 +172,38 @@ cd ..
 cd svn
 if ($dry_run_mode == "off") then
   setenv LANG ja_JP.UTF-8
-  svn commit --file ../$comment_file
+  (svn commit --file ../$comment_file > /dev/null) >& /dev/null
+  if ($? != 0) then
+    echo "ERROR: Svn repository commit error."
+    echo "ERROR: Svn-repository: [$svnrepo/$svnbranch]"
+    exit 6
+  endif
+  setenv LANG C
+else
+  setenv LANG ja_JP.UTF-8
+  (svn status > /dev/null) >& /dev/null
+  if ($? != 0) then
+    echo "ERROR: Svn repository status error."
+    echo "ERROR: Svn-repository: [$svnrepo/$svnbranch]"
+    exit 6
+  endif
   setenv LANG C
 endif
-
-echo "Svn changes:"
-svn status
-echo "Svn commit message: ["
-cat ../$comment_file
-echo "]"
-echo "Last commit hash value: [`cat ../$commit_hash_temp_file`]"
 cd ..
 
 cd ..
 if ($dry_run_mode == "off") then
   mv -f $tempdir/$commit_hash_temp_file $commit_hash_file
 endif
+
+echo "Git-repository: [$gitrepo/$gitbranch]"
+echo "Svn-repository: [$svnrepo/$svnbranch]"
+echo ""
+echo "Saved commit hash value: [$commit_hash_value]"
+echo "Svn commit message: ["
+cat $tempdir/$comment_file
+echo "]"
+
 rm -fr $tempdir
 
-echo ""
-echo "git-repository: [$gitrepo/$gitbranch]"
-echo "svn-repository: [$svnrepo/$svnbranch]"
 echo "Overwrite, OK."
diff --git a/save-commit-hash b/save-commit-hash
--- a/save-commit-hash
+++ b/save-commit-hash
@@ -1,11 +1,5 @@
 #!/bin/csh -fe
 
-if ($1 == "" || $2 == "") then
-  echo "ERROR: Argument error."
-  echo "ERROR: Usage: $ $0 [-f(--commit-hash-file) file_name] git-repo git-branch"
-  exit 1
-endif
-
 setenv LANG C
 
 set gitrepo   = ""
@@ -52,30 +46,39 @@ while ($#argv != 0)
   breaksw
 endsw
 
-echo "git-commit-hash start."
-echo "git-repository: [$gitrepo/$gitbranch]"
-
 set datetime = `date +"%Y%m%d%H%M%S"`
 set tempdir = "temp.$datetime.$$"
 
 set commit_hash_temp_file = ".commit_hash_temp_file"
 
 mkdir -p $tempdir
+
+(git clone -b $gitbranch $gitrepo $tempdir/git > /dev/null) >& /dev/null
+if ($? != 0) then
+  echo "ERROR: Git repository clone error."
+  echo "ERROR: git-repository: [$gitrepo/$gitbranch]"
+  exit 2
+endif
+
 cd $tempdir
-
-git clone -b $gitbranch $gitrepo git
-
 cd git
 git log -1 --pretty=format:"%H" >! ../$commit_hash_temp_file
+if ($? != 0) then
+  echo "ERROR: Git repository log error."
+  echo "ERROR: git-repository: [$gitrepo/$gitbranch]"
+  exit 3
+endif
+set value = `cat ../$commit_hash_temp_file`
 cd ..
 
 cd ..
 mv -f $tempdir/$commit_hash_temp_file $commit_hash_file
+
+echo "Git-repository: [$gitrepo/$gitbranch]"
+echo ""
+echo "Created [$commit_hash_file]."
+echo "Saved commit SHA-1 hash value [$value]."
+
 rm -fr $tempdir
 
-set value = `cat $commit_hash_file`
-
-echo ""
-echo "  Created [$commit_hash_file]."
-echo "  Last commit SHA-1 hash value [$value]."
-echo "OK."
+echo "Save, OK."
